// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import DeleteController from "./delete_controller"
application.register("delete", DeleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import TinymceController from "./tinymce_controller"
application.register("tinymce", TinymceController)
