databases:
  - name: scb-executive-coaching
    ipAllowList: []
    databaseName: scb_executive_coaching
    user: scb_executive_coaching_user

services:
  - type: web
    name: scb_executive_coaching
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scb_executive_coaching
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false