meta_site_name: "SCB Executive Coaching"
meta_title: "Executive Life Coaching"
meta_description: "Life coaching with Stuart Boorman"
meta_image: "profile-pic.webp" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
